lib_LIBRARIES += src/libcodes-storage-server.a

src_libcodes_storage_server_a_SOURCES = \
	src/server/codes-store-lp-api.c \
	src/server/codes-store-pipeline.c \
	src/server/codes-store-pipeline.h \
	src/server/codes-store-lp-impl.c \
	src/server/codes-store-lp-internal.h \
        src/server/codes-ex-store-api.c \
	src/server/codes-ex-store-lp-impl.c
