lib_LIBRARIES += src/libcodes-storage-server.a

src_libcodes_storage_server_a_SOURCES = \
	src/server/codes-store-lp.c \
	src/server/rosd-creq.c \
	src/server/rosd-creq.h \
	src/server/rosd.c \
	src/server/rosd.h
